<span style="color:red; font-family:Georgia; font-size:15px;">
🐼 Pandas

Purpose: Data manipulation and analysis

Key points:

Works mainly with tabular (row-column) data like Excel or SQL tables.

Uses two main structures:

Series → 1D data (like one column)

DataFrame → 2D data (like a table)

Common uses:

Reading data (read_csv, read_excel)

Cleaning data (handling missing values, removing duplicates)

Filtering and grouping (groupby, filter)

Aggregations (sum, mean, count, etc.)


</span>

In [91]:
import pandas as pd
import numpy as np

In [92]:
import matplotlib.pyplot as plt

Reading the data

In [93]:
df= pd.read_csv('/Users/poonamkumari/Downloads/amazon.csv')

In [94]:
pd.set_option('display.max_columns' , None)

In [95]:
df.head(5)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [96]:
df

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [97]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.2+ KB

In [99]:
[r,c]= df.shape

In [100]:
[r,c]

[1465, 16]

In [101]:
data= df.loc[df['product_id']== 'B08HDJ86NZ' ,['product_name', 'category','actual_price']]

In [102]:
data

,product_name,category,actual_price
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹699
392,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹699
628,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹699

In [103]:
df['new_price']= df['actual_price']*2

In [104]:
df.head(1)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,new_price
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,"₹1,099₹1,099"

In [118]:
df.dtypes

product_id             string[python]
product_name           string[python]
category               string[python]
discounted_price              float64
actual_price                  float64
discount_percentage             int64
rating                        float64
rating_count                   object
about_product          string[python]
user_id                string[python]
user_name              string[python]
review_id              string[python]
review_title           string[python]
review_content         string[python]
img_link               string[python]
product_link           string[python]
new_price                      object
dtype: object

In [111]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
new_price              0
dtype: int64

In [115]:
df['product_id']= df['product_id'].astype('string')
df['product_name']= df['product_name'].astype('string')
df['category']= df['category'].astype('string')

# Clean discounted_price column
df['discounted_price'] = df['discounted_price'].astype(str)
df['discounted_price'] = (
    df['discounted_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

# Convert safely to numeric
df['discounted_price'] = pd.to_numeric(df['discounted_price'], errors='coerce')

# Clean actual_price column
df['actual_price'] = df['actual_price'].astype(str)
df['actual_price'] = (
    df['actual_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

# Convert safely to numeric
df['actual_price'] = pd.to_numeric(df['actual_price'], errors='coerce')


df['discount_percentage'] = df['discount_percentage'].astype(str)
df['discount_percentage'] = df['discount_percentage'].str.replace('%', '', regex=False).str.strip()

# Convert safely to numeric
df['discount_percentage'] = pd.to_numeric(df['discount_percentage'], errors='coerce')

df['rating']= pd.to_numeric(df['rating'], errors='coerce')

df['about_product']= df['about_product'].astype('string')
df['user_id']=df['user_id'].astype('string')
df['user_name']= df['user_name'].astype('string')
df['review_id']= df['review_id'].astype('string')
df['review_title']=  df['review_title'].astype('string')
df['review_content']= df['review_content'].astype('string')
df['img_link']= df['img_link'].astype('string')
df['product_link']= df['product_link'].astype('string')

In [ ]:
df.head(1)

In [120]:
df.drop('new_price' , axis=1, inplace=True)

In [121]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

In [122]:
df.dtypes

product_id             string[python]
product_name           string[python]
category               string[python]
discounted_price              float64
actual_price                  float64
discount_percentage             int64
rating                        float64
rating_count                   object
about_product          string[python]
user_id                string[python]
user_name              string[python]
review_id              string[python]
review_title           string[python]
review_content         string[python]
img_link               string[python]
product_link           string[python]
dtype: object

In [123]:
df['rating_count']= df['rating_count'].str.replace(',','')

In [124]:
df['rating_count']= df['rating_count'].astype('float64')

In [125]:
df.dtypes

product_id             string[python]
product_name           string[python]
category               string[python]
discounted_price              float64
actual_price                  float64
discount_percentage             int64
rating                        float64
rating_count                  float64
about_product          string[python]
user_id                string[python]
user_name              string[python]
review_id              string[python]
review_title           string[python]
review_content         string[python]
img_link               string[python]
product_link           string[python]
dtype: object

In [126]:
df['discount_percentage'] = df['discount_percentage'].astype('float64')

In [127]:
df.dtypes

product_id             string[python]
product_name           string[python]
category               string[python]
discounted_price              float64
actual_price                  float64
discount_percentage           float64
rating                        float64
rating_count                  float64
about_product          string[python]
user_id                string[python]
user_name              string[python]
review_id              string[python]
review_title           string[python]
review_content         string[python]
img_link               string[python]
product_link           string[python]
dtype: object

In [129]:
df['rating_count'] = df['rating_count'].fillna(0)

In [130]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 1
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [131]:
df['rating'] = df['rating'].fillna(0)

In [132]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

Returns True if any duplicate row exists in your DataFrame, otherwise False;Returns the number of duplicate rows (excluding the first occurrence);Displays only the duplicated rows (again, excluding the first one).

In [133]:
df.duplicated().any()

np.False_

In [134]:
df.duplicated().sum()

np.int64(0)

In [135]:
df[df.duplicated()]

Empty DataFrame
Columns: [product_id, product_name, category, discounted_price, actual_price, discount_percentage, rating, rating_count, about_product, user_id, user_name, review_id, review_title, review_content, img_link, product_link]
Index: []

In [138]:
df=df.drop_duplicates(subset = ['product_id'], keep='first')

In [139]:
df.head(1)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,24269.0,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...

In [141]:
df['rating'].value_counts()

rating
1.0      2
4.0      1
159.0    1
3.0      1
Name: count, dtype: int64

In [142]:
data_fetched= df.loc[df['rating']==159.0]

In [143]:
data_fetched

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,159.0,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

It's similar to fetching the queries / filtering the data

In [151]:
df.query('rating == 1.0 and product_id=="B07JW9H4J1"')

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,1.0,24269.0,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...

In [154]:
df = df.copy()
df['review_date'] = '2025-11-11'

In [155]:
df.head(5)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,review_date
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,1.0,24269.0,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,2025-11-11
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,NaN,43994.0,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,2025-11-11
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,1.0,7928.0,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...,2025-11-11
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.0,94363.0,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,2025-11-11
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,159.0,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...,2025-11-11

<span style="color:purple; font-family:Georgia; font-size:20px;">
Descriptive Statistics
</span>

In [156]:
df.describe()

,discounted_price,actual_price,discount_percentage,rating,rating_count
count,1351.000000,1351.000000,1351.000000,5.000000,1351.000000
mean,3304.801754,5691.176625,46.685418,33.600000,17618.373797
std,7173.975455,11218.666235,21.632611,70.112766,42119.882419
min,39.000000,39.000000,0.000000,1.000000,0.000000
25%,349.000000,899.000000,31.000000,1.000000,1094.500000
50%,899.000000,1795.000000,49.000000,3.000000,4736.000000
75%,2174.000000,4575.000000,62.000000,4.000000,15995.000000
max,77990.000000,139900.000000,94.000000,159.000000,426973.000000

In [158]:
df.dtypes

product_id             string[python]
product_name           string[python]
category               string[python]
discounted_price              float64
actual_price                  float64
discount_percentage           float64
rating                        float64
rating_count                  float64
about_product          string[python]
user_id                string[python]
user_name              string[python]
review_id              string[python]
review_title           string[python]
review_content         string[python]
img_link               string[python]
product_link           string[python]
review_date                    object
dtype: object

In [159]:
df['review_date']= pd.to_datetime(df['review_date'])

In [162]:
df['review_date'].dtype

dtype('<M8[ns]')

In [163]:
df.dtypes

product_id             string[python]
product_name           string[python]
category               string[python]
discounted_price              float64
actual_price                  float64
discount_percentage           float64
rating                        float64
rating_count                  float64
about_product          string[python]
user_id                string[python]
user_name              string[python]
review_id              string[python]
review_title           string[python]
review_content         string[python]
img_link               string[python]
product_link           string[python]
review_date            datetime64[ns]
dtype: object

In [165]:
df.isnull().sum().sort_values(ascending= False)

rating                 1346
product_id                0
user_id                   0
product_link              0
img_link                  0
review_content            0
review_title              0
review_id                 0
user_name                 0
about_product             0
product_name              0
rating_count              0
discount_percentage       0
actual_price              0
discounted_price          0
category                  0
review_date               0
dtype: int64

In [166]:
round(df.isnull().sum() / len(df) * 100, 2).sort_values(ascending=False)

rating                 99.63
product_id              0.00
user_id                 0.00
product_link            0.00
img_link                0.00
review_content          0.00
review_title            0.00
review_id               0.00
user_name               0.00
about_product           0.00
product_name            0.00
rating_count            0.00
discount_percentage     0.00
actual_price            0.00
discounted_price        0.00
category                0.00
review_date             0.00
dtype: float64

In [177]:
df['rating'] = df.rating_count.fillna(value=np.median(df['rating']))

In [176]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
review_date            0
dtype: int64

Group by

. Built-in Aggregation Functions

These are the most common and directly supported by pandas:

Function	Description
sum()	Sum of values
mean()	Average of values
median()	Median (middle value)
min()	Minimum value
max()	Maximum value
count()	Number of non-NA values
nunique()	Number of unique values
std()	Standard deviation
var()	Variance
prod()	Product of all values
first()	First value in group
last()	Last value in group
sem()	Standard error of mean
size()	Number of rows in group (including NaN)

In [179]:
df.groupby('category')['actual_price'].sum()

category
Car&Motorbike|CarAccessories|InteriorAccessories|AirPurifiers&Ionizers                                                    4000.0
Computers&Accessories|Accessories&Peripherals|Adapters|USBtoUSBAdapters                                                   5398.0
Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCHeadsets                                            999.0
Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCMicrophones                                        2499.0
Computers&Accessories|Accessories&Peripherals|Audio&VideoAccessories|PCSpeakers                                           2799.0
                                                                                                                           ...
OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|GelInkRollerballPens         300.0
OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens      520.0
OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|RetractableBallpointPens     810.0
OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|StickBallpointPens           890.0
Toys&Games|Arts&Crafts|Drawing&PaintingSupplies|ColouringPens&Markers                                                      150.0
Name: actual_price, Length: 211, dtype: float64

In [181]:
df.groupby(['category', 'rating']).agg({'actual_price': ['sum', 'mean'], 'rating_count': 'mean'})

                                                           actual_price  \
                                                                    sum
category                                           rating
Car&Motorbike|CarAccessories|InteriorAccessorie... 1118.0        4000.0
Computers&Accessories|Accessories&Peripherals|A... 1540.0         399.0
                                                   4426.0        4999.0
Computers&Accessories|Accessories&Peripherals|A... 7222.0         999.0
Computers&Accessories|Accessories&Peripherals|A... 2804.0         499.0
...                                                                 ...
OfficeProducts|OfficePaperProducts|Paper|Statio... 5719.0         600.0
OfficeProducts|OfficePaperProducts|Paper|Statio... 2493.0         450.0
                                                   3686.0         320.0
                                                   4308.0         120.0
Toys&Games|Arts&Crafts|Drawing&PaintingSupplies... 15867.0        150.0

                                                                    \
                                                              mean
category                                           rating
Car&Motorbike|CarAccessories|InteriorAccessorie... 1118.0   4000.0
Computers&Accessories|Accessories&Peripherals|A... 1540.0    399.0
                                                   4426.0   4999.0
Computers&Accessories|Accessories&Peripherals|A... 7222.0    999.0
Computers&Accessories|Accessories&Peripherals|A... 2804.0    499.0
...                                                            ...
OfficeProducts|OfficePaperProducts|Paper|Statio... 5719.0    600.0
OfficeProducts|OfficePaperProducts|Paper|Statio... 2493.0    450.0
                                                   3686.0    320.0
                                                   4308.0    120.0
Toys&Games|Arts&Crafts|Drawing&PaintingSupplies... 15867.0   150.0

                                                           rating_count
                                                                   mean
category                                           rating
Car&Motorbike|CarAccessories|InteriorAccessorie... 1118.0        1118.0
Computers&Accessories|Accessories&Peripherals|A... 1540.0        1540.0
                                                   4426.0        4426.0
Computers&Accessories|Accessories&Peripherals|A... 7222.0        7222.0
Computers&Accessories|Accessories&Peripherals|A... 2804.0        2804.0
...                                                                 ...
OfficeProducts|OfficePaperProducts|Paper|Statio... 5719.0        5719.0
OfficeProducts|OfficePaperProducts|Paper|Statio... 2493.0        2493.0
                                                   3686.0        3686.0
                                                   4308.0        4308.0
Toys&Games|Arts&Crafts|Drawing&PaintingSupplies... 15867.0      15867.0

[1195 rows x 3 columns]